namespace Memory.Infrastructure;

/// <summary>Fixed categories only; never stores a route, identifier, tool argument or request body.</summary>
public sealed record ArrivalRequestClassification(string Family, string Method, string PayloadSizeBucket)
{
    private static readonly HashSet<string> Families = new(StringComparer.Ordinal)
    {
        "http-mcp",
        "memory-read",
        "memory-write",
        "context-read",
        "project-read",
        "project-write",
        "work-item-read",
        "work-item-write",
        "discussion-read",
        "discussion-write",
        "governance-read",
        "governance-write",
        "diagnostics-read",
        "diagnostics-write",
        "security-read",
        "security-write",
        "agent-read",
        "agent-write",
        "artifact-read",
        "artifact-write",
        "other-api-read",
        "other-api-write",
        "unknown",
    };

    // Keys are authored endpoint templates, never the request path or route values.
    private static readonly Dictionary<(string Method, string Route), string> HttpFamilies = new()
    {
        [("DELETE", "/api/maintenance/mode")] = "other-api-write",
        [("DELETE", "/api/transfers/{sessionId:guid}")] = "other-api-write",
        [("GET", "/api/actions")] = "other-api-read",
        [("GET", "/api/agent-connectivity/recent")] = "diagnostics-read",
        [("GET", "/api/agent-connectivity/settings")] = "diagnostics-read",
        [("GET", "/api/agent-connectivity/status")] = "diagnostics-read",
        [("GET", "/api/agent-connectivity/summaries")] = "diagnostics-read",
        [("GET", "/api/agent-executions")] = "agent-read",
        [("GET", "/api/agent-executions/dashboard/{projectId}")] = "agent-read",
        [("GET", "/api/agent-executions/{executionId:guid}")] = "agent-read",
        [("GET", "/api/canonical-tags/{projectId}/merge-preview")] = "governance-read",
        [("GET", "/api/canonical-tags/{projectId}/quality")] = "governance-read",
        [("GET", "/api/chatgpt/proposals")] = "other-api-read",
        [("GET", "/api/context/bootstrap")] = "context-read",
        [("GET", "/api/conversations/checkpoints/search")] = "other-api-read",
        [("GET", "/api/conversations/checkpoints/{checkpointId:guid}/pipeline")] = "other-api-read",
        [("GET", "/api/conversations/insights")] = "other-api-read",
        [("GET", "/api/conversations/insights/{insightId:guid}")] = "other-api-read",
        [("GET", "/api/conversations/sessions")] = "other-api-read",
        [("GET", "/api/dashboard/cache-metrics")] = "diagnostics-read",
        [("GET", "/api/dashboard/graph-refresh")] = "diagnostics-read",
        [("GET", "/api/dashboard/monitoring")] = "diagnostics-read",
        [("GET", "/api/dashboard/operations")] = "diagnostics-read",
        [("GET", "/api/dashboard/overview")] = "diagnostics-read",
        [("GET", "/api/dashboard/runtime")] = "diagnostics-read",
        [("GET", "/api/discussions/threads")] = "discussion-read",
        [("GET", "/api/discussions/threads/{threadId:guid}")] = "discussion-read",
        [("GET", "/api/evaluation/runs/{id:guid}")] = "other-api-read",
        [("GET", "/api/evaluation/suites")] = "other-api-read",
        [("GET", "/api/files")] = "artifact-read",
        [("GET", "/api/files/search")] = "artifact-read",
        [("GET", "/api/governance/findings")] = "governance-read",
        [("GET", "/api/jobs")] = "other-api-read",
        [("GET", "/api/jobs/{id:guid}")] = "other-api-read",
        [("GET", "/api/knowledge-reviews/tombstones/{resourceId:guid}")] = "other-api-read",
        [("GET", "/api/logs/search")] = "diagnostics-read",
        [("GET", "/api/logs/{id:long}")] = "diagnostics-read",
        [("GET", "/api/maintenance/runs")] = "other-api-read",
        [("GET", "/api/maintenance/status")] = "other-api-read",
        [("GET", "/api/me")] = "security-read",
        [("GET", "/api/me/tokens")] = "security-read",
        [("GET", "/api/memories")] = "memory-read",
        [("GET", "/api/memories/graph")] = "memory-read",
        [("GET", "/api/memories/projects")] = "memory-read",
        [("GET", "/api/memories/search")] = "memory-read",
        [("GET", "/api/memories/{id:guid}")] = "memory-read",
        [("GET", "/api/memories/{id:guid}/details")] = "memory-read",
        [("GET", "/api/projects/hierarchy/{parentProjectId}")] = "project-read",
        [("GET", "/api/projects/hierarchy/{projectId}/effective-rights")] = "project-read",
        [("GET", "/api/projects/information/")] = "project-read",
        [("GET", "/api/projects/information/{projectId}")] = "project-read",
        [("GET", "/api/secrets")] = "security-read",
        [("GET", "/api/security/audit-events")] = "security-read",
        [("GET", "/api/security/tenants")] = "security-read",
        [("GET", "/api/security/tenants/{tenantId:guid}/project-grants")] = "security-read",
        [("GET", "/api/security/tenants/{tenantId:guid}/tokens")] = "security-read",
        [("GET", "/api/security/tenants/{tenantId:guid}/users")] = "security-read",
        [("GET", "/api/skills")] = "agent-read",
        [("GET", "/api/skills/governance/proposals")] = "agent-read",
        [("GET", "/api/skills/resolutions")] = "agent-read",
        [("GET", "/api/skills/search-generations")] = "agent-read",
        [("GET", "/api/skills/versions/{skillVersionId:guid}/export")] = "agent-read",
        [("GET", "/api/skills/{skillId:guid}")] = "agent-read",
        [("GET", "/api/skills/{skillId:guid}/source-observations")] = "agent-read",
        [("GET", "/api/skills/{skillId:guid}/versions/diff")] = "agent-read",
        [("GET", "/api/sources")] = "other-api-read",
        [("GET", "/api/sources/{id:guid}/runs")] = "other-api-read",
        [("GET", "/api/status")] = "diagnostics-read",
        [("GET", "/api/step-up/requirements")] = "security-read",
        [("GET", "/api/storage/tables")] = "diagnostics-read",
        [("GET", "/api/storage/{table}")] = "diagnostics-read",
        [("GET", "/api/transfers/{sessionId:guid}/content")] = "other-api-read",
        [("GET", "/api/user/preferences")] = "other-api-read",
        [("GET", "/api/work-items")] = "work-item-read",
        [("PATCH", "/api/me/tokens/{tokenId:guid}")] = "security-write",
        [("PATCH", "/api/security/tokens/{tokenId:guid}")] = "security-write",
        [("PATCH", "/api/security/users/{userId:guid}")] = "security-write",
        [("PATCH", "/api/sources/{id:guid}")] = "other-api-write",
        [("PATCH", "/api/user/preferences/{id:guid}")] = "other-api-write",
        [("POST", "/api/actions/{id:guid}/accept")] = "other-api-write",
        [("POST", "/api/actions/{id:guid}/dismiss")] = "other-api-write",
        [("POST", "/api/agent-connectivity/observations")] = "diagnostics-write",
        [("POST", "/api/agent-executions/claim-next")] = "agent-write",
        [("POST", "/api/agent-executions/prepare")] = "agent-write",
        [("POST", "/api/agent-executions/{executionId:guid}/abandon")] = "agent-write",
        [("POST", "/api/agent-executions/{executionId:guid}/block")] = "agent-write",
        [("POST", "/api/agent-executions/{executionId:guid}/cancel")] = "agent-write",
        [("POST", "/api/agent-executions/{executionId:guid}/checkpoints")] = "agent-write",
        [("POST", "/api/agent-executions/{executionId:guid}/complete")] = "agent-write",
        [("POST", "/api/agent-executions/{executionId:guid}/fail")] = "agent-write",
        [("POST", "/api/agent-executions/{executionId:guid}/heartbeat")] = "agent-write",
        [("POST", "/api/agent-executions/{executionId:guid}/resource-approvals")] = "agent-write",
        [("POST", "/api/canonical-tags/telemetry")] = "governance-write",
        [("POST", "/api/canonical-tags/{projectId}/lifecycle")] = "governance-write",
        [("POST", "/api/canonical-tags/{projectId}/merge")] = "governance-write",
        [("POST", "/api/canonical-tags/{projectId}/reconcile")] = "governance-write",
        [("POST", "/api/canonical-tags/{projectId}/split-preview")] = "governance-read",
        [("POST", "/api/chatgpt/proposals/{proposalId:guid}/approve")] = "other-api-write",
        [("POST", "/api/chatgpt/proposals/{proposalId:guid}/reject")] = "other-api-write",
        [("POST", "/api/context/build")] = "context-read",
        [("POST", "/api/conversations/checkpoints/{checkpointId:guid}/process")] = "other-api-write",
        [("POST", "/api/conversations/ingest")] = "other-api-write",
        [("POST", "/api/conversations/insights/promote")] = "other-api-write",
        [("POST", "/api/conversations/insights/{insightId:guid}/disposition")] = "other-api-write",
        [("POST", "/api/conversations/insights/{insightId:guid}/retry")] = "other-api-write",
        [("POST", "/api/conversations/insights/{insightId:guid}/skip")] = "other-api-write",
        [("POST", "/api/discussions/threads")] = "discussion-write",
        [("POST", "/api/discussions/threads/{threadId:guid}/archive")] = "discussion-write",
        [("POST", "/api/discussions/threads/{threadId:guid}/close")] = "discussion-write",
        [("POST", "/api/discussions/threads/{threadId:guid}/messages")] = "discussion-write",
        [("POST", "/api/discussions/threads/{threadId:guid}/read")] = "discussion-write",
        [("POST", "/api/discussions/threads/{threadId:guid}/restore")] = "discussion-write",
        [("POST", "/api/evaluation/runs")] = "other-api-write",
        [("POST", "/api/evaluation/suites")] = "other-api-write",
        [("POST", "/api/files")] = "artifact-write",
        [("POST", "/api/files/{fileId:guid}/delete")] = "artifact-write",
        [("POST", "/api/files/{fileVersionId:guid}/authorize")] = "artifact-write",
        [("POST", "/api/files/{fileVersionId:guid}/quarantine-release")] = "artifact-write",
        [("POST", "/api/files/{fileVersionId:guid}/representations")] = "artifact-write",
        [("POST", "/api/files/{fileVersionId:guid}/security-assessments")] = "artifact-write",
        [("POST", "/api/governance/analyze")] = "governance-write",
        [("POST", "/api/governance/findings/disposition")] = "governance-write",
        [("POST", "/api/governance/findings/reopen")] = "governance-write",
        [("POST", "/api/governance/findings/{id:guid}/accept")] = "governance-write",
        [("POST", "/api/governance/findings/{id:guid}/dismiss")] = "governance-write",
        [("POST", "/api/jobs/reindex")] = "other-api-write",
        [("POST", "/api/jobs/summary-refresh")] = "other-api-write",
        [("POST", "/api/knowledge-reviews")] = "other-api-write",
        [("POST", "/api/knowledge-reviews/execute")] = "other-api-write",
        [("POST", "/api/maintenance/domain-owner-repair/preview")] = "other-api-write",
        [("POST", "/api/maintenance/domain-owner-repair/run")] = "other-api-write",
        [("POST", "/api/maintenance/leases/complete")] = "other-api-write",
        [("POST", "/api/maintenance/leases/heartbeat")] = "other-api-write",
        [("POST", "/api/maintenance/memory-data-retention/run")] = "other-api-write",
        [("POST", "/api/maintenance/mode")] = "other-api-write",
        [("POST", "/api/maintenance/retrieval-telemetry-retention/run")] = "other-api-write",
        [("POST", "/api/maintenance/vacuum-full-reclaim/run")] = "other-api-write",
        [("POST", "/api/maintenance/windows")] = "other-api-write",
        [("POST", "/api/maintenance/windows/current/cancel")] = "other-api-write",
        [("POST", "/api/maintenance/windows/current/complete")] = "other-api-write",
        [("POST", "/api/maintenance/windows/current/drain")] = "other-api-write",
        [("POST", "/api/maintenance/windows/current/start")] = "other-api-write",
        [("POST", "/api/maintenance/windows/{runId:guid}/cancel")] = "other-api-write",
        [("POST", "/api/maintenance/windows/{runId:guid}/complete")] = "other-api-write",
        [("POST", "/api/maintenance/windows/{runId:guid}/drain")] = "other-api-write",
        [("POST", "/api/maintenance/windows/{runId:guid}/start")] = "other-api-write",
        [("POST", "/api/me/tokens")] = "security-write",
        [("POST", "/api/me/tokens/{tokenId:guid}/regenerate")] = "security-write",
        [("POST", "/api/me/tokens/{tokenId:guid}/revoke")] = "security-write",
        [("POST", "/api/memories/export")] = "memory-read",
        [("POST", "/api/memories/graph/index/refresh")] = "memory-write",
        [("POST", "/api/memories/import/apply")] = "memory-write",
        [("POST", "/api/memories/import/preview")] = "memory-read",
        [("POST", "/api/memories/project-cleanup/apply")] = "memory-write",
        [("POST", "/api/memories/project-cleanup/preview")] = "memory-read",
        [("POST", "/api/memories/{id:guid}/archive")] = "memory-write",
        [("POST", "/api/memories/{id:guid}/delete")] = "memory-write",
        [("POST", "/api/memories/{id:guid}/move")] = "memory-write",
        [("POST", "/api/memories/{id:guid}/restore")] = "memory-write",
        [("POST", "/api/performance/measure")] = "diagnostics-write",
        [("POST", "/api/projects/information/{projectId}/lifecycle")] = "project-write",
        [("POST", "/api/secrets")] = "security-write",
        [("POST", "/api/secrets/ssh/sign-authentication")] = "security-write",
        [("POST", "/api/secrets/{secretId:guid}/leases")] = "security-write",
        [("POST", "/api/secrets/{secretId:guid}/revoke")] = "security-write",
        [("POST", "/api/secrets/{secretId:guid}/versions")] = "security-write",
        [("POST", "/api/security/tenants")] = "security-write",
        [("POST", "/api/security/tenants/{tenantId:guid}/tokens")] = "security-write",
        [("POST", "/api/security/tenants/{tenantId:guid}/users")] = "security-write",
        [("POST", "/api/security/tokens/{tokenId:guid}/regenerate")] = "security-write",
        [("POST", "/api/security/tokens/{tokenId:guid}/revoke")] = "security-write",
        [("POST", "/api/skills/analytics")] = "agent-write",
        [("POST", "/api/skills/analytics/reconcile")] = "agent-write",
        [("POST", "/api/skills/analytics/trend")] = "agent-write",
        [("POST", "/api/skills/governance/proposals/{proposalId:guid}/decision")] = "agent-write",
        [("POST", "/api/skills/governance/review")] = "agent-write",
        [("POST", "/api/skills/import")] = "agent-write",
        [("POST", "/api/skills/import/preview")] = "agent-write",
        [("POST", "/api/skills/invocations")] = "agent-write",
        [("POST", "/api/skills/materializations/cleanup")] = "agent-write",
        [("POST", "/api/skills/materialize")] = "agent-write",
        [("POST", "/api/skills/reindex")] = "agent-write",
        [("POST", "/api/skills/resolution-feedback")] = "agent-write",
        [("POST", "/api/skills/search-for-execution")] = "agent-write",
        [("POST", "/api/skills/search-generations/{generationId:guid}/activate")] = "agent-write",
        [("POST", "/api/skills/select-for-execution")] = "agent-write",
        [("POST", "/api/skills/version-get")] = "agent-write",
        [("POST", "/api/skills/versions/{skillVersionId:guid}/lifecycle")] = "agent-write",
        [("POST", "/api/skills/versions/{skillVersionId:guid}/publish")] = "agent-write",
        [("POST", "/api/skills/{skillId:guid}/source-observations")] = "agent-write",
        [("POST", "/api/sources")] = "other-api-write",
        [("POST", "/api/sources/{id:guid}/sync")] = "other-api-write",
        [("POST", "/api/ssh-certificates")] = "security-write",
        [("POST", "/api/ssh-certificates/{certificateLeaseId:guid}/renew")] = "security-write",
        [("POST", "/api/ssh-certificates/{certificateLeaseId:guid}/revoke")] = "security-write",
        [("POST", "/api/step-up/password")] = "security-write",
        [("POST", "/api/step-up/recovery-code/regenerate")] = "security-write",
        [("POST", "/api/step-up/recovery-code/verify")] = "security-write",
        [("POST", "/api/step-up/totp/enrollment")] = "security-write",
        [("POST", "/api/step-up/totp/enrollment/confirm")] = "security-write",
        [("POST", "/api/step-up/totp/verify")] = "security-write",
        [("POST", "/api/step-up/totp/{factorId:guid}/remove")] = "security-write",
        [("POST", "/api/step-up/webauthn/authentication/complete")] = "security-write",
        [("POST", "/api/step-up/webauthn/authentication/options")] = "security-write",
        [("POST", "/api/step-up/webauthn/registration/complete")] = "security-write",
        [("POST", "/api/step-up/webauthn/registration/options")] = "security-write",
        [("POST", "/api/step-up/webauthn/{credentialId:guid}/remove")] = "security-write",
        [("POST", "/api/transfers/downloads")] = "other-api-write",
        [("POST", "/api/transfers/uploads")] = "other-api-write",
        [("POST", "/api/transfers/{sessionId:guid}/complete")] = "other-api-write",
        [("POST", "/api/user/preferences")] = "other-api-write",
        [("POST", "/api/work-items")] = "work-item-write",
        [("POST", "/api/work-items/{id:guid}/archive")] = "work-item-write",
        [("POST", "/api/work-items/{id:guid}/restore")] = "work-item-write",
        [("PUT", "/api/projects/hierarchy/{parentProjectId}")] = "project-write",
        [("PUT", "/api/projects/information/{projectId}")] = "project-write",
        [("PUT", "/api/security/tenants/{tenantId:guid}/project-grants/{projectId}")] = "security-write",
        [("PUT", "/api/skills/{skillId:guid}/bindings")] = "agent-write",
        [("PUT", "/api/skills/{skillId:guid}/default")] = "agent-write",
        [("PUT", "/api/transfers/{sessionId:guid}/chunks/{chunkIndex:int}")] = "other-api-write",
        [("PUT", "/api/work-items/{id:guid}")] = "work-item-write",
        [("PUT", "/api/work-items/{workItemId:guid}/checklist/{checklistItemId:guid}")] = "work-item-write",
        [("PUT", "/api/work-items/{workItemId:guid}/governance-exclusion")] = "work-item-write",
    };

    // Exact names from the published catalogs. Future/unknown tools remain unknown.
    private static readonly Dictionary<string, string> ToolFamilies = new(StringComparer.Ordinal)
    {
        ["agent_execution_abandon"] = "agent-write",
        ["agent_execution_block"] = "agent-write",
        ["agent_execution_checkpoint"] = "agent-write",
        ["agent_execution_claim_next"] = "agent-write",
        ["agent_execution_complete"] = "agent-write",
        ["agent_execution_fail"] = "agent-write",
        ["agent_execution_get"] = "agent-read",
        ["agent_execution_heartbeat"] = "agent-write",
        ["agent_execution_prepare"] = "agent-write",
        ["build_working_context"] = "context-read",
        ["chatgpt_governance_proposal_create"] = "other-api-write",
        ["chatgpt_proposal_approve"] = "other-api-write",
        ["chatgpt_proposal_reject"] = "other-api-write",
        ["chatgpt_proposals_list"] = "other-api-read",
        ["conversation_ingest"] = "other-api-write",
        ["conversation_insight_retry"] = "other-api-write",
        ["conversation_insight_set_disposition"] = "other-api-write",
        ["conversation_insight_skip"] = "other-api-write",
        ["conversation_insight_status"] = "other-api-read",
        ["conversation_insights_list"] = "other-api-read",
        ["conversation_sessions_list"] = "other-api-read",
        ["daily_memory_review"] = "other-api-read",
        ["describe_context_hub"] = "context-read",
        ["discussion_message_create"] = "discussion-write",
        ["discussion_thread_archive"] = "discussion-write",
        ["discussion_thread_close"] = "discussion-write",
        ["discussion_thread_create"] = "discussion-write",
        ["discussion_thread_get"] = "discussion-read",
        ["discussion_thread_restore"] = "discussion-write",
        ["discussion_threads_list"] = "discussion-read",
        ["enqueue_reindex"] = "other-api-write",
        ["enqueue_summary_refresh"] = "other-api-write",
        ["governance_batch_execute"] = "governance-write",
        ["governance_contract_get"] = "governance-read",
        ["governance_finding_reopen"] = "governance-write",
        ["governance_finding_set_disposition"] = "governance-write",
        ["governance_run_get"] = "governance-read",
        ["governance_runs_list"] = "governance-read",
        ["governance_tombstone_get"] = "governance-read",
        ["knowledge_review"] = "governance-write",
        ["log_read"] = "diagnostics-read",
        ["log_search"] = "diagnostics-read",
        ["maintenance_lease_complete"] = "diagnostics-write",
        ["maintenance_lease_heartbeat"] = "diagnostics-write",
        ["maintenance_status"] = "diagnostics-read",
        ["managed_file_register"] = "artifact-write",
        ["managed_files_list"] = "artifact-read",
        ["managed_files_search"] = "artifact-read",
        ["memory_archive"] = "memory-write",
        ["memory_delete"] = "memory-write",
        ["memory_get"] = "memory-read",
        ["memory_move"] = "memory-write",
        ["memory_restore"] = "memory-write",
        ["memory_retention_preview"] = "memory-read",
        ["memory_search"] = "memory-read",
        ["memory_update"] = "memory-write",
        ["memory_upsert"] = "memory-write",
        ["project_artifact_get"] = "artifact-read",
        ["project_artifact_publish"] = "artifact-write",
        ["project_artifacts_list"] = "artifact-read",
        ["project_artifacts_search"] = "artifact-read",
        ["project_cleanup_apply"] = "project-write",
        ["project_cleanup_preview"] = "project-read",
        ["project_hierarchy_get_children"] = "project-read",
        ["project_hierarchy_set_children"] = "project-write",
        ["project_information_get"] = "project-read",
        ["project_information_update_lifecycle"] = "project-write",
        ["project_information_upsert"] = "project-write",
        ["project_work_item_archive"] = "work-item-write",
        ["project_work_item_checklist_update"] = "work-item-write",
        ["project_work_item_create"] = "work-item-write",
        ["project_work_item_restore"] = "work-item-write",
        ["project_work_item_set_governance_exclusion"] = "work-item-write",
        ["project_work_item_update"] = "work-item-write",
        ["project_work_items_list"] = "work-item-read",
        ["projects_list"] = "project-read",
        ["promote_log_slice_to_memory"] = "other-api-write",
        ["scheduled_governance_contract_get"] = "governance-read",
        ["scheduled_governance_execute"] = "governance-write",
        ["scheduled_governance_review"] = "governance-write",
        ["scheduled_governance_run_get"] = "governance-read",
        ["skill_version_get"] = "agent-read",
        ["skill_version_materialize"] = "agent-write",
        ["skills_invocation_record"] = "agent-write",
        ["skills_materialization_cleanup"] = "agent-write",
        ["skills_resolution_feedback"] = "agent-write",
        ["skills_search_for_execution"] = "agent-read",
        ["skills_select_for_execution"] = "agent-write",
        ["suggested_action_accept"] = "other-api-write",
        ["suggested_action_dismiss"] = "other-api-write",
        ["suggested_actions_list"] = "other-api-read",
        ["user_preference_archive"] = "other-api-write",
        ["user_preference_list"] = "other-api-read",
        ["user_preference_upsert"] = "other-api-write",
        ["user_preferences_list"] = "other-api-read",
    };

    public static ArrivalRequestClassification Normalize(ArrivalRequestClassification? value)
        => new(value?.Family is { } family && Families.Contains(family) ? family : "unknown",
            NormalizeMethod(value?.Method),
            value?.PayloadSizeBucket switch
            {
                "empty" or "le1k" or "le16k" or "le256k" or "le4m" or "gt4m" => value.PayloadSizeBucket,
                _ => "unknown"
            });

    public static ArrivalRequestClassification ForHttp(string? method, string? endpointTemplate, long? contentLength,
        bool mcpEnvelope = false)
    {
        var normalizedMethod = NormalizeMethod(method);
        var family = mcpEnvelope ? "http-mcp"
            : endpointTemplate is not null && HttpFamilies.TryGetValue((normalizedMethod, endpointTemplate), out var known)
                ? known : "unknown";
        return new(family, normalizedMethod, SizeBucket(contentLength));
    }

    public static ArrivalRequestClassification ForTool(string? toolName)
        => new(toolName is not null && ToolFamilies.TryGetValue(toolName, out var family) ? family : "unknown",
            "UNKNOWN", "unknown");

    private static string NormalizeMethod(string? method)
        => method switch
        {
            "GET" or "POST" or "PUT" or "PATCH" or "DELETE" or "HEAD" or "OPTIONS" => method,
            _ => "UNKNOWN"
        };

    // Declared Content-Length only; unknown for streaming/chunked bodies. Never measure by reading the body.
    private static string SizeBucket(long? contentLength)
        => contentLength switch
        {
            null or < 0 => "unknown",
            0 => "empty",
            <= 1024 => "le1k",
            <= 16 * 1024 => "le16k",
            <= 256 * 1024 => "le256k",
            <= 4 * 1024 * 1024 => "le4m",
            _ => "gt4m"
        };
}

/// <summary>Observability failure must never change an HTTP or MCP dispatch result.</summary>
public static class RequestArrivalCapture
{
    public static RequestArrivalLease? TryBegin(RequestArrivalObservations? observations,
        string layer, string operation, long parentSequence = 0, ArrivalRequestClassification? classification = null)
    {
        try { return observations?.Begin(layer, operation, parentSequence, classification); }
        catch (Exception) { return null; }
    }

    public static void TryComplete(RequestArrivalLease? observation, string outcome)
    {
        try { observation?.Complete(outcome); }
        catch (Exception) { /* Capture remains best-effort without logging request data or exception text. */ }
    }
}
